package com.amerkhaled.bookingsystem.mappers.impl;

import com.amerkhaled.bookingsystem.domain.dto.UserRequestDto;
import com.amerkhaled.bookingsystem.domain.dto.UserResponseDto;
import com.amerkhaled.bookingsystem.domain.dto.UserUpdateDto;
import com.amerkhaled.bookingsystem.domain.entities.User;
import com.amerkhaled.bookingsystem.mappers.UserMapper;
import org.springframework.stereotype.Component;

@Component
public class UserMapperImpl implements UserMapper {

    @Override
    public User fromRequestDto(UserRequestDto userRequestDto) {
        return new User(
                null, // Password Generated by Database
                userRequestDto.name(),
                userRequestDto.email(),
                userRequestDto.password(),
                userRequestDto.role()
        );
    }

    @Override
    public User fromUpdateDto(UserUpdateDto userUpdateDto) {
        return new User(
                userUpdateDto.id(),
                userUpdateDto.name(),
                userUpdateDto.email(),
                userUpdateDto.password(),
                userUpdateDto.role()

        );
    }

    @Override
    public UserResponseDto toResponseDto(User user) {
        return new UserResponseDto(
                user.getId(),
                user.getName(),
                user.getEmail(),
                user.getRole()
        );
    }

}
